# development:
#   adapter: async

# test:
#   adapter: async


redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

  # production: *redis
production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: _runforrestrun_production

  development: *redis

  test: *redis
