# development:
#   adapter: async

# test:
#   adapter: async


redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: _runforrestrun_production

development: *redis

test: *redis
