meta_product_name: "Run, Forrest! Run!"

meta_title: "Run Forrest Run - Tweet #runforrestrun to make Forrest Gump run another mile across America."

meta_description: "We're recreating Forrest Gump's 13,089 mile run.
                  Every time #runforrestrun is used on Twitter, Forrest Gump runs another mile.
                  In 1979 it took him 3 years, 2 months, 14 days, and 16 hours.
                  Let's see if we can't beat that."

meta_image: "running.jpg"

twitter_account: "@tristanviney"
